### ISSUE TITLE
How to reference variables of other code blocks

### ISSUE THREAD

**Issue by dzylikecode** [jhildenbiddle/docsify-plugin-runkit#1]
I want to use the plugin to replace Jupyter. 

- code block 1

  ```js
  let a = 1;
  ```

- code blog 2

  ```js
  console.log(a);
  ```
  
  how to make it work

**Comment by jhildenbiddle** [comment]
Hi @dzylikecode --

I don't believe there is a way to share data between separate notebooks. These suggestions might get you close to what you're looking for though:

1. Runkit notebooks created on runkit.com allow you share data between code blocks, but the presentation of the embedded notebook may not be what you want:
   - Example: https://runkit.com/tonic/es6-arrow-functions
   - Embed: `<div data-runkit="https://runkit.com/tonic/es6-arrow-functions"></div>`
2. Runkit's `preamble` option might allow you to "fake" code sharing depending on how complex your needs are. From the [documentation](https://runkit.com/docs/embed):
   > Code in the preamble field will not be displayed in the embed, but will be
   > executed before running the code in the embed. For example, libraries that use
   > RunKit for documentation often require their package in the preamble to avoid
   > clutter in the embed code.

   Example:

   ````html
   <div data-runkit data-runkit-preamble="var test = 'foo';">

   ```javascript
   console.log(test);
   ```

   </div>
   ````

Hope this helps.

**Comment by dzylikecode** [comment]
Thanks for your help.
